export const mockCategories = [
  { id: 'popular', name: 'Popular' },
  { id: 'burgers', name: 'Burgers' },
  { id: 'wraps', name: 'Wraps' },
  { id: 'sides', name: 'Sides' },
  { id: 'drinks', name: 'Drinks' },
  { id: 'desserts', name: 'Desserts' },
]

export const mockMenuItems = [
  {
    id: 'sd-b1',
    name: 'Classic Chicken Burger',
    description: 'Crispy chicken, lettuce, and signature sauce.',
    price: 179,
    imageUrl: '',
    categoryId: 'burgers',
    isVeg: false,
    spiceLevel: 1,
    tags: ['popular', 'crispy'],
    available: true,
  },
  {
    id: 'sd-b2',
    name: 'Paneer Tikka Burger',
    description: 'Grilled paneer tikka, onions, and mint mayo.',
    price: 169,
    imageUrl: '',
    categoryId: 'burgers',
    isVeg: true,
    spiceLevel: 2,
    tags: ['popular', 'veg'],
    available: true,
  },
  {
    id: 'sd-b3',
    name: 'Spicy Peri Peri Burger',
    description: 'Peri peri chicken, crunchy slaw, peri mayo.',
    price: 199,
    imageUrl: '',
    categoryId: 'burgers',
    isVeg: false,
    spiceLevel: 3,
    tags: ['spicy', 'popular'],
    available: true,
  },
  {
    id: 'sd-w1',
    name: 'Grilled Chicken Wrap',
    description: 'Grilled chicken, fresh veggies, creamy sauce.',
    price: 189,
    imageUrl: '',
    categoryId: 'wraps',
    isVeg: false,
    spiceLevel: 1,
    tags: ['light'],
    available: true,
  },
  {
    id: 'sd-w2',
    name: 'Falafel Wrap',
    description: 'Crispy falafel, hummus, pickled onions.',
    price: 159,
    imageUrl: '',
    categoryId: 'wraps',
    isVeg: true,
    spiceLevel: 1,
    tags: ['veg', 'light'],
    available: true,
  },
  {
    id: 'sd-s1',
    name: 'Masala Fries',
    description: 'Fries tossed in house masala seasoning.',
    price: 99,
    imageUrl: '',
    categoryId: 'sides',
    isVeg: true,
    spiceLevel: 2,
    tags: ['popular', 'snack'],
    available: true,
  },
  {
    id: 'sd-s2',
    name: 'Cheesy Nachos',
    description: 'Corn chips, cheese sauce, jalapeños.',
    price: 139,
    imageUrl: '',
    categoryId: 'sides',
    isVeg: true,
    spiceLevel: 1,
    tags: ['share'],
    available: true,
  },
  {
    id: 'sd-s3',
    name: 'Chicken Nuggets (6 pcs)',
    description: 'Bite-sized nuggets with dip.',
    price: 149,
    imageUrl: '',
    categoryId: 'sides',
    isVeg: false,
    spiceLevel: 0,
    tags: ['kids', 'share'],
    available: true,
  },
  {
    id: 'sd-d1',
    name: 'Cola',
    description: 'Chilled and fizzy.',
    price: 59,
    imageUrl: '',
    categoryId: 'drinks',
    isVeg: true,
    spiceLevel: 0,
    tags: ['cold'],
    available: true,
  },
  {
    id: 'sd-d2',
    name: 'Lemon Iced Tea',
    description: 'Refreshing lemon iced tea.',
    price: 79,
    imageUrl: '',
    categoryId: 'drinks',
    isVeg: true,
    spiceLevel: 0,
    tags: ['cold'],
    available: true,
  },
  {
    id: 'sd-d3',
    name: 'Mango Shake',
    description: 'Thick mango shake with ice cream.',
    price: 129,
    imageUrl: '',
    categoryId: 'drinks',
    isVeg: true,
    spiceLevel: 0,
    tags: ['sweet'],
    available: true,
  },
  {
    id: 'sd-de1',
    name: 'Choco Lava Cake',
    description: 'Warm chocolate cake with molten center.',
    price: 119,
    imageUrl: '',
    categoryId: 'desserts',
    isVeg: true,
    spiceLevel: 0,
    tags: ['sweet', 'popular'],
    available: true,
  },
]

